In [1]:
print('hello world')

hello world


**Discriminant Analysis** using Multi-variate Regression

In [3]:
#libraries
import numpy as np
import scipy.stats as ss

In [37]:
a = int(input('number of input variables:'))
X = []

for i in range(a):
    l = list(map(float,input(f'input for row {i+1} : ').split(',')))
    X.append(l)

one = []
for i in range(len(X[0])):
    one.append(1)
X.append(one)

Y = list(input('Output Variable: ').split())
for i in range(len(Y)):
    if Y[i].capitalize() == 'Yes':
        Y[i] = 1
    elif Y[i].capitalize() == 'No':
        Y[i] = 0
    else:
        print('Invalid input!')

print(X)

print(Y)
X[0] ,X[-1],X[1] = X[1],X[0],X[-1]

[[1300.0, 1260.0, 1220.0, 1180.0, 1060.0, 1140.0, 1100.0, 1020.0, 980.0, 940.0], [2.7, 3.7, 2.9, 2.5, 3.9, 2.1, 3.5, 3.3, 2.3, 3.1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]


In [43]:
print(X)
XN = np.array(X).transpose()
print(XN)

[[2.7, 3.7, 2.9, 2.5, 3.9, 2.1, 3.5, 3.3, 2.3, 3.1], [1300.0, 1260.0, 1220.0, 1180.0, 1060.0, 1140.0, 1100.0, 1020.0, 980.0, 940.0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
[[2.70e+00 1.30e+03 1.00e+00]
 [3.70e+00 1.26e+03 1.00e+00]
 [2.90e+00 1.22e+03 1.00e+00]
 [2.50e+00 1.18e+03 1.00e+00]
 [3.90e+00 1.06e+03 1.00e+00]
 [2.10e+00 1.14e+03 1.00e+00]
 [3.50e+00 1.10e+03 1.00e+00]
 [3.30e+00 1.02e+03 1.00e+00]
 [2.30e+00 9.80e+02 1.00e+00]
 [3.10e+00 9.40e+02 1.00e+00]]


In [35]:
print(X)

[[1300.0, 1260.0, 1220.0, 1180.0, 1060.0, 1140.0, 1100.0, 1020.0, 980.0, 940.0], [2.7, 3.7, 2.9, 2.5, 3.9, 2.1, 3.5, 3.3, 2.3, 3.1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
