**Discriminant Analysis** using Multi-variate Regression

In [ ]:
#libraries
import numpy as np
import scipy.stats as ss

In [77]:
a = int(input('number of input variables:'))
X = []

for i in range(a):
    l = list(map(float,input(f'input for row {i+1} : ').split()))
    X.append(l)

one = []
for i in range(len(X[0])):
    one.append(1)
X.append(one)

Y = list(input('Output Variable: ').split())
for i in range(len(Y)):
    if Y[i].capitalize() == 'Yes':
        Y[i] = 1
    elif Y[i].capitalize() == 'No':
        Y[i] = 0
    else:
        print('Invalid input!')

print(X)

print(Y)
X[1],X[0],X[-1] = X[0] ,X[-1],X[1]
print(X)

[[2.95, 2.53, 3.57, 3.16, 2.58, 2.16, 3.27], [6.63, 7.79, 5.65, 5.47, 4.46, 6.22, 3.52], [1, 1, 1, 1, 1, 1, 1]]
[1, 1, 1, 1, 0, 0, 0]
[[1, 1, 1, 1, 1, 1, 1], [2.95, 2.53, 3.57, 3.16, 2.58, 2.16, 3.27], [6.63, 7.79, 5.65, 5.47, 4.46, 6.22, 3.52]]


In [78]:
print(X)
XN = np.array(X).transpose()
print(XN)

[[1, 1, 1, 1, 1, 1, 1], [2.95, 2.53, 3.57, 3.16, 2.58, 2.16, 3.27], [6.63, 7.79, 5.65, 5.47, 4.46, 6.22, 3.52]]
[[1.   2.95 6.63]
 [1.   2.53 7.79]
 [1.   3.57 5.65]
 [1.   3.16 5.47]
 [1.   2.58 4.46]
 [1.   2.16 6.22]
 [1.   3.27 3.52]]


In [79]:
Xt = XN.transpose()
B = np.matmul((np.linalg.inv(np.matmul(Xt,XN))),np.matmul(Xt,Y))

for i in range(len(B)):
    B[i] = round(B[i],4)
print(B)


[-3.9116  0.8533  0.3555]


In [82]:
ex = list(map(float,input('Enter the Observation to be Evaluated : ').split()))

ans = (B[0]+(B[1]*ex[0])+(B[2]*ex[1]))
an = round(ans)
print('Yes' if an == 1 else 'No')


No
