In [112]:
import numpy as np

In [113]:
g,p = map(int,input('Enter number of Groups and number of Variables').split())
T = []

for i in range(g):
    gi = []
    for j in range(p):
        li = list(map(float,input(f'input grp: {i+1} and var : {j+1} : ').split()))
        gi.append(li)
    T.append(np.array(gi).transpose())

T

[array([[1300. ,    2.7],
        [1260. ,    3.7],
        [1220. ,    2.9],
        [1180. ,    2.5],
        [1060. ,    3.9]]),
 array([[1140. ,    2.1],
        [1100. ,    3.5],
        [1020. ,    3.3],
        [ 980. ,    2.3],
        [ 940. ,    3.1]])]

In [114]:
from tkinter import PROJECTING


ux = []
for i in T:
    ui = np.mean(i,axis=0)
    ux.append(ui)
ux = np.array(ux)
print("mean of groups-->\n",ux)

F = []
for i in T:
    F.extend(i)

X = np.array(F)
u = np.mean(X,axis=0)
print('X---> mean of X -->')
print(X,u,sep='\n')
X_u = []
for i in X:
    X_u.append(i-u)
X_u = np.array(X_u)
print('X-U-->',X_u,sep='\n')


mean of groups-->
 [[1204.      3.14]
 [1036.      2.86]]
X---> mean of X -->
[[1300.     2.7]
 [1260.     3.7]
 [1220.     2.9]
 [1180.     2.5]
 [1060.     3.9]
 [1140.     2.1]
 [1100.     3.5]
 [1020.     3.3]
 [ 980.     2.3]
 [ 940.     3.1]]
[1120.    3.]
X-U-->
[[ 1.8e+02 -3.0e-01]
 [ 1.4e+02  7.0e-01]
 [ 1.0e+02 -1.0e-01]
 [ 6.0e+01 -5.0e-01]
 [-6.0e+01  9.0e-01]
 [ 2.0e+01 -9.0e-01]
 [-2.0e+01  5.0e-01]
 [-1.0e+02  3.0e-01]
 [-1.4e+02 -7.0e-01]
 [-1.8e+02  1.0e-01]]


In [115]:
n = len(X)
print(n)

10


In [116]:
c = np.matmul(X_u.transpose(),X_u)/n

print('pooled Co-var: \n',c)
cinv = np.linalg.inv(c)
print('c^-1 = :\n',cinv)

pooled Co-var: 
 [[ 1.32e+04 -2.80e+00]
 [-2.80e+00  3.30e-01]]
c^-1 = :
 [[7.58941713e-05 6.43950545e-04]
 [6.43950545e-04 3.03576685e+00]]


In [117]:
ex = np.array(list(map(float,input('Enter the Observation to be Evaluated : ').split()))).transpose()
ex = ex.reshape(p,1)
print(ex)

[[1000. ]
 [   2.9]]


In [118]:
from cmath import log

pp = input('Is probabilities given:')
if pp.capitalize == 'Yes':
    pr = list(map(float,input('Enter::').split()))
    pr = [0.25,0.25,0.5]
else:
    pr = [len(T[i])/n for i in range(g)]

print('probs : ',pr)

f = []

for i in range(g):
    ucxt = np.matmul(np.matmul(ux[i],cinv),ex)
    ucut = ((np.matmul(np.matmul(ux[i],cinv),ux[i].transpose())))
    ln = log(pr[i])
    # print(ucxt,ucut,ln)
    f.append(ucxt-0.5*ucut+ln)

mx = max(f)
for i in range(g):
    if f[i] == mx:
        print(f'{ex} belongs to group {i+1}')
# print(f)

probs :  [0.5, 0.5]
[[1000. ]
 [   2.9]] belongs to group 2
