In [1]:
print('hello world')

hello world


In [ ]:
#manova one way construction

In [158]:
import numpy as np
from math import prod,sqrt
from statistics import mean
from numpy.linalg import det
import scipy.stats as ss


In [39]:
k = int(input("Total number of treatments"))
los = 0.05
n = 0
Tr = []
for i in range(k):
    T1 = []
    nSub = int(input(f'Number of Sub treatments of Tr {i+1}:'))
    n += nSub
    for j in range(nSub):
        l = list(map(int,input('Enter Sub groups:').split()))
        T1.append(l)
    Tr.append(T1)
    p = len(T1[0])


print(Tr)
print(f'n: {n} :: k: {k} :: p:{p}')

[[[9, 3], [6, 2], [9, 7]], [[0, 4], [2, 0]], [[3, 8], [1, 9], [2, 7]]]
n: 8 :: k: 3 :: p:2


In [160]:
cr = []
for i in Tr:
    cri = []
    for j in i:
        cri.append(prod(j))
    cr.append(cri)
print(cr)

[[27, 12, 63], [0, 0], [24, 9, 14]]


In [105]:
y__ = []

for x in range(p):
    v = 0
    mm = 0
    for i in Tr:
        mi = []
        for j in i:
            mm+=j[x]
            v+=1
    y__.append(mm/v)
print(y__)

M__ = prod(y__)
print(M__)

[4.0, 5.0]
20.0


In [110]:
yi = []
for i in Tr:
    yii = []
    for x in range(p):
        yiii = 0
        c = 0
        for j in i:
            # print(j[x])
            c+=1
            yiii+=j[x]
        yii.append(yiii/c)
        # print('##')
    # print(yii)
    yi.append(yii)
    # print('>>')
print(yi)


M = []
for i in yi:
    M.append(prod(i))
print(M)

[[8.0, 4.0], [1.0, 2.0], [2.0, 8.0]]
[32.0, 2.0, 16.0]


In [119]:
##SSE
SSE = []
for x in range(p):
    SSEi = 0
    for i in range(len(Tr)):
        for j in range(len(Tr[i])):
            SSEi+=(Tr[i][j][x]-yi[i][x])**2
            # print(Tr[i][j][x],'-',yi[i][x])
    SSE.append(SSEi)
print(SSE)

SSEc = 0
for i in range(len(cr)):
    for j in range(len(cr[i])):
        # print(cr[i][j],M[i])
        SSEc+=(cr[i][j]-M[i])
SSE.append(SSEc)

print(SSE)


[10.0, 24.0]
[10.0, 24.0, 1.0]


In [118]:
##SST
SST = []
for x in range(p):
    SSTi = 0
    for i in range(len(Tr)):
        for j in range(len(Tr[i])):
            SSTi+=(Tr[i][j][x]-y__[x])**2
            # print(Tr[i][j][x],'-',y__[x])
    SST.append(SSTi)
print(SST)

SSTc = 0
for i in range(len(cr)):
    for j in range(len(cr[i])):
        # print(cr[i][j],M[i])
        SSTc+=(cr[i][j]-M__)
SST.append(SSTc)

print(SST)


[88.0, 72.0]
[88.0, 72.0, -11.0]


In [120]:
SSR = []
for i,j in zip(SST,SSE):
    SSR.append(i-j)
print(SSR)

[78.0, 48.0, -12.0]


In [141]:
srcvar = [SSR,SSE,SST]
sos = [0,0,0]
degFre = [k-1,n-k,n-1]

In [142]:
for i in range(len(srcvar)):
    sos[i]= (np.array([[srcvar[i][0],srcvar[i][2]],[srcvar[i][2],srcvar[i][1]]],dtype=int))

B = sos[0]
W = sos[1]
T = sos[2]
print(B,W,T,sep='\n')

[[ 78 -12]
 [-12  48]]
[[10  1]
 [ 1 24]]
[[ 88 -11]
 [-11  72]]


In [163]:
A = det(W)/det(T)
Fcal = ((n-k-1)*(1-sqrt(A)))/((k-1)*(sqrt(A)))
print(f'Fcalualated: {Fcal}')

Fcalualated: 8.198859563778381


In [162]:
Ftab = ss.f.ppf(1-los,p*(k-1),p*(n-k-1))
print(f'Ftable: {Ftab}')

Ftable: 3.837853354555897


In [164]:
if Ftab<Fcal:
    print('We Reject H0')
else:
    print('We accept H0')

We Reject H0
