In [1]:
import numpy as np

In [25]:
def transpose(matrix):
    x = matrix.shape
    m_new = np.zeros(x,int)
    # print(m_new)
    for i in range(x[0]):
        for j in range(x[1]):
            m_new[i][j] = matrix[j][i]
    
    return (m_new)
        

In [90]:
matrix = np.array([[1,2,3],[3,4,5],[5,6,7]])
mt=transpose(matrix)
print(f'The matrix is ::\n{m} \n The transpose is ::\n{mt}')
i = 0
matrix[1:,1:]

The matrix is ::
[[1, 2, 4], [4, 5, 6], [6, 7, 8]] 
 The transpose is ::
[[1 3 5]
 [2 4 6]
 [3 5 7]]


array([[4, 5],
       [6, 7]])

In [94]:
def det22(m):
    if m.shape == (2,2):
        return m[0][0]*m[1][1] - m[1][0]*m[0][1]

In [146]:
def det(matrix):
    x = matrix.shape
    det = 0
            
    if x == (2,2):
        return det22(matrix)
    elif x == (3,3):

        for i in range(x[0]):
            #submatrix creation
            ms = np.copy(matrix)
            ms = ms[1:]
            ms = np.concatenate([ms[:,:i],ms[:,i+1:]],axis=1)
            
            # print(ms)
            # print(det22(ms))
            
            # det caluclation
            if i%2 == 0:
                det += matrix[0][i]*det22(ms)
            else:
                det -= matrix[0][i]*det22(ms)
                
        return det
    else:
        print('Invalid Matrix to calculate the Determinant')
        return None

In [148]:
ms = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ms)
det(ms)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
-3
[[4 6]
 [7 9]]
-6
[[4 5]
 [7 8]]
-3


0