<h1 style='color:cyan;'>Multi Linear Regression<h1>

In [2]:
def line():
    print('-------------------------------------------------------------------------------------')

In [66]:
##Library
import numpy as np
import scipy.stats as ss
import math

In [7]:
#input cell

y = np.array(list(map(int,input('enter y').split())))
x1 = np.array(list(map(int,input('enter x1').split())))
x2 = np.array(list(map(int,input('enter x2').split())))

In [48]:
x0 = np.ones(len(x1),int)
xt = np.array([x0,x1,x2])
x = xt.transpose()
y = y.reshape([len(y),1])
x, y, xt
los = 0.05

In [62]:
## b = ((xt*x)**-1)*(xt*y)
## b1 = xt*x
## b2 = xt*y 
## b1inv = inv(b1)


b1 = np.dot(xt,x)
b1inv = np.linalg.inv(b1)
cjj = [b1inv[i][i] for i in range(3)]
b2 = np.dot(xt,y)

b = np.dot(b1inv,b2)
print(b)
ans = b.reshape([len(b)])
print(ans)
print(cjj)

[[133.46048243]
 [ -1.24850346]
 [ -0.35100837]]
[133.46048243  -1.24850346  -0.35100837]
[40.89440259769005, 0.011751452364648463, 0.012314726867089485]


In [10]:
yExp = []

for i,j in zip(x1,x2):
    yExp.append((ans[0]+ans[1]*i+ans[2]*j))

yExp = np.array(yExp)
yExp = yExp.reshape([len(yExp),1])
yExp

array([[100.46143226],
       [103.11396921],
       [102.25642243],
       [ 94.92093172],
       [ 96.36491352],
       [100.96797067],
       [105.41549778],
       [108.80999978],
       [105.25996775],
       [105.80645446],
       [104.71348104],
       [104.90895938]])

In [11]:
epsil = y - yExp
print(epsil)

[[-0.46143226]
 [ 6.88603079]
 [ 2.74357757]
 [-0.92093172]
 [-1.36491352]
 [-1.96797067]
 [-1.41549778]
 [-0.80999978]
 [-0.25996775]
 [-7.80645446]
 [ 0.28651896]
 [ 5.09104062]]


In [12]:
ybar = np.mean(y)
ybar

102.75

In [13]:
sst = sum((y-ybar)**2)[0]
sse = sum(epsil**2)[0]
ssr = sst-sse

sse,ssr,sst

(151.41040622031764, 178.83959377968236, 330.25)

In [14]:
R2 = ssr/sst
R2

0.5415279145486218

In [15]:
import pandas as pd
val={
    'x1':x1,
    'x2':x2,
    'observed y':y.transpose()[0],
    'expected y':yExp.transpose()[0],
    'error':epsil.transpose()[0]
}
print(f'The model is : y = {ans[0]}+({ans[1]})*x1+({ans[2]})*x2')
line()
df = pd.DataFrame(val)
print(df)
line()
print(f'mean sum of squares due to \n -->regression {ssr}\n -->total {sst} \n -->error {sse}')
line()
print(f'The coefficient of Determination is R2 : {R2}')
line()
if(R2>0.9):
    print('As R2 is greater than 0.9, the model is a goodfit')
else:
    print('As R2 is less than 0.9, the model is not a goodfit')

The model is : y = 133.46048242804682+(-1.2485034569591562)*x1+(-0.351008371805392)*x2
-------------------------------------------------------------------------------------
    x1  x2  observed y  expected y     error
0    9  62         100  100.461432 -0.461432
1    8  58         110  103.113969  6.886031
2    7  64         105  102.256422  2.743578
3   14  60          94   94.920932 -0.920932
4   12  63          95   96.364914 -1.364914
5   10  57          99  100.967971 -1.967971
6    7  55         104  105.415498 -1.415498
7    4  56         108  108.810000 -0.810000
8    6  59         105  105.259968 -0.259968
9    5  61          98  105.806454 -7.806454
10   7  57         105  104.713481  0.286519
11   6  60         110  104.908959  5.091041
-------------------------------------------------------------------------------------
mean sum of squares due to 
 -->regression 178.83959377968236
 -->total 330.25 
 -->error 151.41040622031764
-----------------------------------------------

<h3>ANOVA Test</h3>

In [16]:
##ANOVA test

# h0 : bj = 0
# h1 : bj != 0
# los = 0.05

degFre = {
    # number of variable - 1 =  
    'p-1':3-1,
    # number of observation  - 1 =  
    'n-1':len(y)-1,
    # n-p
    'n-p':len(y)-3
}

degFre





{'p-1': 2, 'n-1': 11, 'n-p': 9}

In [42]:
val = {
    'src of var' : ['Regression','Error'],
    'Sum of sqr' : [ssr,sse],
    'Deg Fre'     : [degFre['p-1'],degFre['n-p']],
}

anova = pd.DataFrame(val)
anova

src of var  Sum of sqr  Deg Fre
0  Regression  178.839594        2
1       Error  151.410406        9

In [43]:
total = ['total',sum(anova['Sum of sqr']),sum(anova['Deg Fre'])]
anova.loc[len(anova)] = total
anova

src of var  Sum of sqr  Deg Fre
0  Regression  178.839594        2
1       Error  151.410406        9
2       total  330.250000       11

In [44]:
meanss = anova['Sum of sqr']/anova['Deg Fre']
anova['Mean sos'] =meanss[:2]
varRatio = anova['Mean sos'][0]/anova['Mean sos'][1]
anova['Var Ratio'] = ['',varRatio,'']

anova

src of var  Sum of sqr  Deg Fre   Mean sos Var Ratio
0  Regression  178.839594        2  89.419797          
1       Error  151.410406        9  16.823378   5.31521
2       total  330.250000       11        NaN

In [59]:
Ftab = ss.f.ppf(1-los,anova['Deg Fre'][0],anova['Deg Fre'][1])
Fcal = anova['Var Ratio'][1]
print(f'The F calculated value is: {Fcal}')
line()
print(f'The F table value is: {Ftab}')
line()
print('We can say that:')
if Ftab>Fcal:
    print('The model has no contributing variables')
else:
    print('Model has contributing variables')

The F calculated value is: 5.315210440935849
-------------------------------------------------------------------------------------
The F table value is: 4.25649472909375
-------------------------------------------------------------------------------------
We can say that:
Model has contributing variables


<h3>Test of Individual Parameters</h3>

In [80]:
ms2e = anova['Mean sos'][1]

val = {
    'predictors':['B0','B1','B2'],
    'co-efficients':[b[i][0] for i in range(len(b))],
    'standard error':[math.sqrt(ms2e*i) for i in cjj],
}
T = pd.DataFrame(val)
T

predictors  co-efficients  standard error
0         B0     133.460482       26.229411
1         B1      -1.248503        0.444634
2         B2      -0.351008        0.455165

In [81]:
T['t'] = T['co-efficients']/T['standard error']
T

predictors  co-efficients  standard error         t
0         B0     133.460482       26.229411  5.088200
1         B1      -1.248503        0.444634 -2.807937
2         B2      -0.351008        0.455165 -0.771167

In [90]:
Ttab = ss.t.ppf(1-los/2,anova['Deg Fre'][1])
print(f'The table value is {Ttab}')
line()
for i in range(len(T['t'])):
    if abs(T['t'][i])>Ttab:
        print(f'B{i} contributes to the model')
    else:
        print(f'B{i} does not contributes to the model')
    line()

The table value is 2.2621571627409915
-------------------------------------------------------------------------------------
B0 contributes to the model
-------------------------------------------------------------------------------------
B1 contributes to the model
-------------------------------------------------------------------------------------
B2 does not contributes to the model
-------------------------------------------------------------------------------------
