In [167]:
def line():
    print('-------------------------------------------------------------------------------------')

<h1 style='color:cyan;'>Multi Linear Regression<h1>

In [112]:
##Library
import numpy as np

In [27]:
#input cell

y = np.array(list(map(int,input('enter y').split())))
x1 = np.array(list(map(int,input('enter x1').split())))
x2 = np.array(list(map(int,input('enter x2').split())))

In [115]:
x0 = np.ones(len(x1),int)
xt = np.array([x0,x1,x2])
x = xt.transpose()
y = y.reshape([len(y),1])
x, y, xt

(array([[ 1,  9, 62],
        [ 1,  8, 58],
        [ 1,  7, 64],
        [ 1, 14, 60],
        [ 1, 12, 63],
        [ 1, 10, 57],
        [ 1,  7, 55],
        [ 1,  4, 56],
        [ 1,  6, 59],
        [ 1,  5, 61],
        [ 1,  7, 57],
        [ 1,  6, 60]]),
 array([[100],
        [110],
        [105],
        [ 94],
        [ 95],
        [ 99],
        [104],
        [108],
        [105],
        [ 98],
        [105],
        [110]]),
 array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 9,  8,  7, 14, 12, 10,  7,  4,  6,  5,  7,  6],
        [62, 58, 64, 60, 63, 57, 55, 56, 59, 61, 57, 60]]))

In [121]:
## b = ((xt*x)**-1)*(xt*y)
## b1 = xt*x
## b2 = xt*y 
## b1inv = inv(b1)


b1 = np.dot(xt,x)
b1inv = np.linalg.inv(b1)

b2 = np.dot(xt,y)

b = np.dot(b1inv,b2)
print(b)
ans = b.reshape([len(b)])
print(ans)

[[133.46048243]
 [ -1.24850346]
 [ -0.35100837]]
[133.46048243  -1.24850346  -0.35100837]


In [133]:
yExp = []

for i,j in zip(x1,x2):
    yExp.append((ans[0]+ans[1]*i+ans[2]*j))

yExp = np.array(yExp)
yExp = yExp.reshape([len(yExp),1])
yExp

array([[100.46143226],
       [103.11396921],
       [102.25642243],
       [ 94.92093172],
       [ 96.36491352],
       [100.96797067],
       [105.41549778],
       [108.80999978],
       [105.25996775],
       [105.80645446],
       [104.71348104],
       [104.90895938]])

In [134]:
epsil = y - yExp
print(epsil)

[[-0.46143226]
 [ 6.88603079]
 [ 2.74357757]
 [-0.92093172]
 [-1.36491352]
 [-1.96797067]
 [-1.41549778]
 [-0.80999978]
 [-0.25996775]
 [-7.80645446]
 [ 0.28651896]
 [ 5.09104062]]


In [139]:
ybar = np.mean(y)
ybar

102.75

In [155]:
sst = sum((y-ybar)**2)[0]
sse = sum(epsil**2)[0]
ssr = sst-sse

sse,ssr,sst

(151.41040622031764, 178.83959377968236, 330.25)

In [143]:
R2 = ssr/sst
R2

0.5415279145486218

In [170]:
import pandas as pd
val={
    'x1':x1,
    'x2':x2,
    'observed y':y.transpose()[0],
    'expected y':yExp.transpose()[0],
    'error':epsil.transpose()[0]
}
print(f'The model is : y = {ans[0]}+({ans[1]})*x1+({ans[2]})*x2')
line()
df = pd.DataFrame(val)
print(df)
line()
print(f'mean sum of squares due to \n -->regression {ssr}\n -->total {sst} \n -->error {sse}')
line()
print(f'The coefficient of Determination is R2 : {R2}')
line()
if(R2>0.9):
    print('As R2 is greater than 0.9, the model is a goodfit')
else:
    print('As R2 is less than 0.9, the model is not a goodfit')

The model is : y = 133.46048242804682+(-1.2485034569591562)*x1+(-0.351008371805392)*x2
-------------------------------------------------------------------------------------
    x1  x2  observed y  expected y     error
0    9  62         100  100.461432 -0.461432
1    8  58         110  103.113969  6.886031
2    7  64         105  102.256422  2.743578
3   14  60          94   94.920932 -0.920932
4   12  63          95   96.364914 -1.364914
5   10  57          99  100.967971 -1.967971
6    7  55         104  105.415498 -1.415498
7    4  56         108  108.810000 -0.810000
8    6  59         105  105.259968 -0.259968
9    5  61          98  105.806454 -7.806454
10   7  57         105  104.713481  0.286519
11   6  60         110  104.908959  5.091041
-------------------------------------------------------------------------------------
mean sum of squares due to 
 -->regression 178.83959377968236
 -->total 330.25 
 -->error 151.41040622031764
-----------------------------------------------

In [173]:
##ANOVA test

# h0 : bj = 0
# h1 : bj != 0
# los = 0.05

degFre = {
    # number of variable - 1 =  
    'p-1':3-1,
    # number of observation  - 1 =  
    'n-1':len(y)-1,
    # n-p
    'n-p':len(y)-3
}

degFre





{'p-1': 2, 'n-1': 11, 'n-p': 9}

In [175]:
val = {
    'src of var' : ['Regression','Error'],
    'Sum of sqr' : [ssr,sse],
    'Deg Fre'     : [degFre['p-1'],degFre['n-p']],
}

anova = pd.DataFrame(val)
anova

src of var  Sum of sqr  Deg Fre
0  Regression  178.839594        2
1       Error  151.410406        9

In [178]:
total = ['total',sum(anova['Sum of sqr']),sum(anova['Deg Fre'])]
anova.loc[len(anova)] = total
anova

src of var  Sum of sqr  Deg Fre
0  Regression  178.839594        2
1       Error  151.410406        9
2       total  330.250000       11

In [ ]:
meanss = 