In [19]:
import numpy as np

In [20]:
x = np.array(list(map(float,input().split())))
y = np.array(list(map(float,input().split())))

In [22]:
x,y

(array([0., 1., 2., 3., 4.]), array([1. , 1.8, 1.3, 2.5, 6.3]))

In [24]:
xy = x*y
x2 = x**2
x3 = x**3
x4 = x**4
x2y = (x**2 )*y


xy,x2,x3,x4,x2y

(array([ 0. ,  1.8,  2.6,  7.5, 25.2]),
 array([ 0.,  1.,  4.,  9., 16.]),
 array([ 0.,  1.,  8., 27., 64.]),
 array([  0.,   1.,  16.,  81., 256.]),
 array([  0. ,   1.8,   5.2,  22.5, 100.8]))

In [26]:
tx = sum(x)
ty = sum(y)
txy = sum(xy)
tx2 = sum(x2)
tx3 = sum(x3)
tx4 = sum(x4)
tx2y = sum(x2y)

tx,ty,txy,tx2,tx3,tx4,tx2y

(10.0, 12.899999999999999, 37.1, 30.0, 100.0, 354.0, 130.3)

In [28]:
n = len(x)
n

5

In [41]:
m = [[n,tx,tx2],[tx,tx2,tx3],[tx2,tx3,tx4]]
p = [ty,txy,tx2y]

m = np.array(m)
p = np.array(p)

m,p

(array([[  5.,  10.,  30.],
        [ 10.,  30., 100.],
        [ 30., 100., 354.]]),
 array([ 12.9,  37.1, 130.3]))

In [42]:
def copycol(m,p,i):
    n = np.copy(m)
    n[:,i] = p
    return n


In [43]:
copycol(m,p,0)

array([[ 12.9,  10. ,  30. ],
       [ 37.1,  30. , 100. ],
       [130.3, 100. , 354. ]])

In [46]:
from numpy.linalg import det

d = det(m)

m1 = copycol(m,p,0)
m2 = copycol(m,p,1)
m3 = copycol(m,p,2)

a,b,c = det(m1)/d,det(m2)/d,det(m3)/d

a,b,c = round(a,3),round(b,3),round(c,3)

a,b,c

(1.42, -1.07, 0.55)