In [2]:
def line():
    print('-------------------------------------------------------------------------------')

**Principal Component Analysis**

In [28]:
import numpy as np
import pandas as pd

In [11]:
n = int(input('Number of variables'))
x = []

for i in range(n):
    x.append(list(map(int,input(f'variable {i+1}').split())))
m = len(x[0])
x = np.transpose(x)
print(x,m)


[[90 60 90]
 [90 90 30]
 [60 60 60]
 [60 60 90]
 [30 30 30]] 5


In [13]:
u = np.mean(x,axis=0)
xu = x-u
C = np.matmul(np.transpose(xu),xu)/m
C

array([[504., 360., 180.],
       [360., 360.,   0.],
       [180.,   0., 720.]])

In [20]:
lam,e = np.linalg.eig(C)

print('Eigen values:',lam,'Eigen Vectors:',e,sep='\n')
evct = e.transpose()
print('Eigen vectors right way:\n',evct)

for i in range(len(evct)):
    v = 0
    for j in range(len(evct[0])):
        if evct[i][j]< 0:
            v+=1
    
    if v == len(evct):
        evct[i] = -1*evct[i]

        
print('corrected eigen vector:\n',evct)

Eigen values:
[ 44.81966028 910.06995304 629.11038668]
Eigen Vectors:
[[ 0.6487899  -0.65580225 -0.3859988 ]
 [-0.74104991 -0.4291978  -0.51636642]
 [-0.17296443 -0.62105769  0.7644414 ]]
Eigen vectors right way:
 [[ 0.6487899  -0.74104991 -0.17296443]
 [-0.65580225 -0.4291978  -0.62105769]
 [-0.3859988  -0.51636642  0.7644414 ]]
corrected eigen vector:
 [[ 0.6487899  -0.74104991 -0.17296443]
 [ 0.65580225  0.4291978   0.62105769]
 [-0.3859988  -0.51636642  0.7644414 ]]


In [34]:
eval = -np.sort(-lam)
print(eval)
z = []
ind = []
for i in eval:
    for j in range(len(lam)):
        if i == lam[j]:
            ind.append(j)

for i in ind:
    z.append(evct[i])
z = np.array(z)
print(z)

[910.06995304 629.11038668  44.81966028]
[[ 0.65580225  0.4291978   0.62105769]
 [-0.3859988  -0.51636642  0.7644414 ]
 [ 0.6487899  -0.74104991 -0.17296443]]


In [33]:
val ={
    'PC':['z'+f'{i+1}' for i in range(len(eval))],
    'var exp':eval
}

ans = pd.DataFrame(val)
zx = []
s = 0
tt = sum(eval)
for i in eval:
    s+=i
    zx.append(s/tt)
ans['cummulate var'] = zx
ans

PC     var exp  cummulate var
0  z1  910.069953       0.574539
1  z2  629.110387       0.971705
2  z3   44.819660       1.000000

In [49]:
indx = 0
for i in range(len(zx)):
    print(zx[i])
    if zx[i] > 0.90:
        indx = i
        break
print(indx)
res = []
for i in range(indx+1):
    resi = []
    for j in x:
        print(j,z[i])
        for r,t in zip(j,z[i]):
            


0.5745391117683308
0.9717047599225765
1
[90 60 90] [0.65580225 0.4291978  0.62105769]
[90 90 30] [0.65580225 0.4291978  0.62105769]
[60 60 60] [0.65580225 0.4291978  0.62105769]
[60 60 90] [0.65580225 0.4291978  0.62105769]
[30 30 30] [0.65580225 0.4291978  0.62105769]
[90 60 90] [-0.3859988  -0.51636642  0.7644414 ]
[90 90 30] [-0.3859988  -0.51636642  0.7644414 ]
[60 60 60] [-0.3859988  -0.51636642  0.7644414 ]
[60 60 90] [-0.3859988  -0.51636642  0.7644414 ]
[30 30 30] [-0.3859988  -0.51636642  0.7644414 ]
