In [25]:
def line():
    print('-------------------------------------------------------------------------------')

**Principal Component Analysis**

In [26]:
import numpy as np
import pandas as pd

In [27]:
n = int(input('Number of variables'))
x = []

for i in range(n):
    x.append(list(map(int,input(f'variable {i+1}').split())))
m = len(x[0])
x = np.transpose(x)
print(x,m)


[[ 3  6  5]
 [ 7  3  3]
 [10  9  8]
 [ 3  9  7]
 [10  6  5]] 5


In [28]:
u = np.mean(x,axis=0)
xu = x-u
C = np.matmul(np.transpose(xu),xu)/m
C

array([[ 9.84, -0.36,  0.44],
       [-0.36,  5.04,  3.84],
       [ 0.44,  3.84,  3.04]])

In [29]:
lam,e = np.linalg.eig(C)

print('Eigen values:',lam,'Eigen Vectors:',e,sep='\n')
evct = e.transpose()
print('Eigen vectors right way:\n',evct)

for i in range(len(evct)):
    v = 0
    for j in range(len(evct[0])):
        if evct[i][j]< 0:
            v+=1
    
    if v == len(evct):
        evct[i] = -1*evct[i]

        
print('corrected eigen vector:\n',evct)

Eigen values:
[0.03897648 9.87308342 8.00794009]
Eigen Vectors:
[[-0.05788553 -0.9982878   0.00841062]
 [-0.61061578  0.04206905  0.79080881]
 [ 0.78980861 -0.04064073  0.61200547]]
Eigen vectors right way:
 [[-0.05788553 -0.61061578  0.78980861]
 [-0.9982878   0.04206905 -0.04064073]
 [ 0.00841062  0.79080881  0.61200547]]
corrected eigen vector:
 [[-0.05788553 -0.61061578  0.78980861]
 [-0.9982878   0.04206905 -0.04064073]
 [ 0.00841062  0.79080881  0.61200547]]


In [30]:
eval = -np.sort(-lam)
print(eval)
z = []
ind = []
for i in eval:
    for j in range(len(lam)):
        if i == lam[j]:
            ind.append(j)

for i in ind:
    z.append(evct[i])
z = np.array(z)
print(z)

[9.87308342 8.00794009 0.03897648]
[[-0.9982878   0.04206905 -0.04064073]
 [ 0.00841062  0.79080881  0.61200547]
 [-0.05788553 -0.61061578  0.78980861]]


In [31]:
val ={
    'PC':['z'+f'{i+1}' for i in range(len(eval))],
    'var exp':eval
}

ans = pd.DataFrame(val)
zx = []
s = 0
tt = sum(eval)
for i in eval:
    s+=i
    zx.append(s/tt)
ans['cummulate var'] = zx
ans

PC   var exp  cummulate var
0  z1  9.873083       0.550953
1  z2  8.007940       0.997825
2  z3  0.038976       1.000000

In [33]:
indx = 0
for i in range(len(zx)):
    print(zx[i])
    if zx[i] > 0.90:
        indx = i
        break
print(indx)
res = []
for i in range(indx+1):
    resi = []
    for j in x:
        # print(j,z[i])
        s = 0
        for r,t in zip(j,z[i]):
            s+=r*t
        resi.append(abs(s))
    res.append(resi)
res = np.transpose(res)
print(res)


0.5509533160100639
0.9978249730732559
1
[[ 2.94565277  7.83011205]
 [ 6.98372964  4.26731718]
 [ 9.92938241 12.09742923]
 [ 2.9007271  11.4265494 ]
 [ 9.93366735  7.88898641]]
