<style>
    h1{
        color:gray;
        background:white;
        display:flex;
        justify-content:center;
        height: 200px;  
        align-items:center;
    }
</style>
<h1>ANOVA TWO WAY</h1>

In [31]:
import numpy as np
import pandas as pd
import scipy.stats as ss

In [32]:
K = int(input('Enter Number of treatments:'))
F = []
for i in range(K):
    F.append(list(map(int,input(f'treatment{i+1}:').split())))

In [41]:
F = np.array(F)
los = 0.05
print(F)

[[45 43 51]
 [47 46 52]
 [48 50 55]
 [42 37 49]]


In [62]:

T = np.sum(F,axis=1)
B = np.sum(F,axis=0)
G = sum(T)
T2 = np.square(T)
B2 = np.square(B)
ST2 = sum(T2)
SB2 = sum(B2)
Finv = F.transpose()
inp = pd.DataFrame(F)
inp['T'] = T
inp['T^2'] = T2
print(inp)
res = [T,B,G,T2,B2,ST2,SB2]
res

    0   1   2    T    T^2
0  45  43  51  139  19321
1  47  46  52  145  21025
2  48  50  55  153  23409
3  42  37  49  128  16384


[array([139, 145, 153, 128]),
 array([182, 176, 207]),
 565,
 array([19321, 21025, 23409, 16384], dtype=int32),
 array([33124, 30976, 42849], dtype=int32),
 80139,
 106949]

In [43]:
deg_fre = [k,h] = [len(res[0]),len(res[1])]
RSS = np.sum(np.square(F.flatten()))
CF = G**2/(k*h)
SST = RSS - CF
SSTR = ST2/h - CF
SSB = SB2/k - CF
SSE = SST - SSTR - SSB

[deg_fre,RSS,CF,SST,SSTR,SSB,SSE]

[[4, 3],
 26867,
 26602.083333333332,
 264.9166666666679,
 110.91666666666788,
 135.16666666666788,
 18.83333333333212]

In [44]:
vals = {
    'Source of Variance':['Treatments','Blocks','Errors'],
    'Sum of Sqauares':[SSTR,SSB,SSE],
    'Degree of Freedom':[deg_fre[0]-1,deg_fre[1]-1,(deg_fre[0]-1)*(deg_fre[1]-1)]
}

df = pd.DataFrame(vals)
df['Mean sum of Squares'] = df['Sum of Sqauares']/df['Degree of Freedom']
df['Variance Ratio'] = df['Mean sum of Squares']/df['Mean sum of Squares'][2]
print('The ANOVA Two way table :: ')
df

The ANOVA Two way table :: 


Source of Variance  Sum of Sqauares  Degree of Freedom  Mean sum of Squares  \
0         Treatments       110.916667                  3            36.972222   
1             Blocks       135.166667                  2            67.583333   
2             Errors        18.833333                  6             3.138889   

   Variance Ratio  
0       11.778761  
1       21.530973  
2        1.000000

In [45]:
##INFERENCE

# treatment

FTtab = ss.f.ppf(1-los,df['Degree of Freedom'][0],df['Degree of Freedom'][2])
FBtab = ss.f.ppf(1-los,df['Degree of Freedom'][1],df['Degree of Freedom'][2])

if FTtab>df['Variance Ratio'][0]:
    print("Accept H0 for treatments")
else: print("Reject H0 for treatments")
 
if FBtab>df['Variance Ratio'][1]:
    print("Accept H0 for Blocks")
else: print("Reject H0 for Blocks")


Reject H0 for treatments
Reject H0 for Blocks
