In [5]:
!pip install scipy

In [83]:
import numpy as np
import math
import scipy.stats as ss
import pandas as pd

In [27]:
def freq(x):
    fx= {}
    for i in x:
        if i in fx:
          fx[i] += 1
        else:
            fx[i] = 1  
    return fx

In [15]:
def rank(x):
    rank = ss. rankdata(x)
    return len(x) - rank + 1
        

In [99]:
def disq(x,y):
    rankx = rank(x)
    ranky = rank(y)
    di = (rankx-ranky)
    disq = di**2
    tdsq = sum(disq)
    
    #correction factor
    cf = 0
    for i,j in freq(x).items():
        if j != 1:
            cf += j*((j**2)- 1)/12
            
    for i,j in freq(y).items():
        if j != 1:
            cf += j*((j**2)- 1)/12
            
    tdsq += cf
    
    return [rankx,ranky,di,disq,tdsq]
    

In [81]:
def rankcorr(x,y):
    res = disq(x,y)
    rou = 1 - ((6*res[-1])/(n*(n**2 - 1)))
    return round(rou,5)

In [77]:

x =  np.array(list(map(int,input("Enter x:").split())))
y =  np.array(list(map(int,input("Enter y:").split())))
n = len(x)


In [78]:
print(x,y,n,len(y))

[81 78 73 73 69 68 62 58] [10 12 18 18 18 22 20 24] 8 8


In [100]:
res = disq(x,y)
res[0],x

(array([1. , 2. , 3.5, 3.5, 5. , 6. , 7. , 8. ]),
 array([81, 78, 73, 73, 69, 68, 62, 58]))

In [82]:
rankcorr(x,y)

-0.92857

In [156]:
data = pd.DataFrame()
data['x'] = x
data['y'] = y
data['Rank x'] = res[0]
data['Rank y'] = res[1]
data['di'] = res[2]
data['di^2'] = res[3]
rowsum = data.iloc[:,6].sum()
# data.add()
data.loc['Total'] = rowsum
print(data)


IndexError: single positional indexer is out-of-bounds